---
abstract: unknown
author:
  - 'Andre Garcia Carneiro <andregarciacarneiro@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Memcached-Queue
no_index:
  directory:
    - t
    - inc
requires:
  Cache::Memcached::Fast: 0
  Data::Serializer: 0
  Data::UUID::MT: 0
  Moose: 0
  Test::More: 0
  common::sense: 0
  feature: 0
version: v0.1.4
